/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "server_node.h"

// Added from peer_node.h
bool_t
xdr_file_packet (XDR *xdrs, file_packet *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->bytes, 2048,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_file_update (XDR *xdrs, file_update *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->mode))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->file_name, MAXNAME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_host_info (XDR *xdrs, host_info *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->ip, 16,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->port))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_file_info (XDR *xdrs, file_info *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->name, MAXNAME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->hosts, MAXHOST,
		sizeof (host_info), (xdrproc_t) xdr_host_info))
		 return FALSE;
	return TRUE;
}

// Added from peer node
bool_t
xdr_download_1_argument (XDR *xdrs, download_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->file_name, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->idx))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_check_client_update_1_argument (XDR *xdrs, check_client_update_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->ip, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->port))
		 return FALSE;
	return TRUE;
}

