/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SERVER_NODE_H_RPCGEN
#define _SERVER_NODE_H_RPCGEN

#include <rpc/rpc.h>
#include "rpc_call.h"

#ifdef __cplusplus
extern "C" {
#endif

#define MAXSIZE 1024
#define MAXNAME 256
#define MAXHOST 10

#define NEW 1
#define DEL 2
#define UPD 3  // update?  maybe something for later...

struct file_packet {
	int size;
	char bytes[MAXSIZE];
};
typedef struct file_packet file_packet;


struct file_update {
	int mode;
	char file_name[MAXNAME];
};
typedef struct file_update file_update;


struct host_info {
	char ip[16];
	int port;
};
typedef struct host_info host_info;


struct file_info {
	char name[MAXNAME];
	host_info hosts[MAXHOST];
};
typedef struct file_info file_info;


struct download_1_argument {
	char *file_name;
	int idx;
};
typedef struct download_1_argument download_1_argument;


struct check_client_update_1_argument {
	char *ip;
	int port;
};
typedef struct check_client_update_1_argument check_client_update_1_argument;

#define SERVER_NODE_PROG 1000
#define SERVER_NODE_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define download 1
#define update_list 2
#define list_hosts_str 1
extern  file_info * list_hosts_str_1(char *, CLIENT *);
extern  file_info * list_hosts_str_1_svc(char *, struct svc_req *);
#define list_hosts_num 2
extern  file_info * list_hosts_num_1(int , CLIENT *);
extern  file_info * list_hosts_num_1_svc(int , struct svc_req *);
#define check_client_update 3
extern  void * check_client_update_1(char *, int , CLIENT *);
extern  void * check_client_update_1_svc(char *, int , struct svc_req *);
#define find_host 4
extern  host_info * find_host_1(char *, CLIENT *);
extern  host_info * find_host_1_svc(char *, struct svc_req *);
#define Ping 99
extern  bool_t * ping_1(CLIENT *);
extern  bool_t * ping_1_svc(struct svc_req *);
extern int server_node_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define download 1
#define list_hosts_str 1
extern  file_info * list_hosts_str_1();
extern  file_info * list_hosts_str_1_svc();
#define list_hosts_num 2
extern  file_info * list_hosts_num_1();
extern  file_info * list_hosts_num_1_svc();
#define check_client_update 3
extern  void * check_client_update_1();
extern  void * check_client_update_1_svc();
#define find_host 4
extern  host_info * find_host_1();
extern  host_info * find_host_1_svc();
#define Ping 99
extern  bool_t * ping_1();
extern  bool_t * ping_1_svc();
extern int server_node_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_file_packet (XDR *, file_packet*);
extern  bool_t xdr_file_packet (XDR *, file_packet*);
extern  bool_t xdr_file_update (XDR *, file_update*);
extern  bool_t xdr_file_update (XDR *, file_update*);
extern  bool_t xdr_host_info (XDR *, host_info*);
extern  bool_t xdr_host_info (XDR *, host_info*);
extern  bool_t xdr_file_info (XDR *, file_info*);
extern  bool_t xdr_file_info (XDR *, file_info*);
extern  bool_t xdr_download_1_argument (XDR *, download_1_argument*);
extern  bool_t xdr_check_client_update_1_argument (XDR *, check_client_update_1_argument*);

#else /* K&R C */
extern bool_t xdr_file_packet ();
extern bool_t xdr_file_packet ();
extern bool_t xdr_file_update ();
extern bool_t xdr_file_update ();
extern bool_t xdr_host_info ();
extern bool_t xdr_host_info ();
extern bool_t xdr_file_info ();
extern bool_t xdr_file_info ();
extern bool_t xdr_download_1_argument ();
extern bool_t xdr_check_client_update_1_argument ();

#endif /* K&R C */


////////// INCLUDES FROM peer_node.h //////////

#define PEER_NODE_PROG 1000
#define PEER_NODE_VERSION 1

#define get_version 3
#define get_update 4
#define getLoad 5

////////// END EXTRA INCLUDES //////////

#ifdef __cplusplus
}
#endif

#endif /* !_SERVER_NODE_H_RPCGEN */
