/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PEER_NODE_H_RPCGEN
#define _PEER_NODE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXSIZE 1024
#define MAXNAME 256

// latency def
unsigned int latency;

struct file_packet {
	int size;
	char bytes[MAXSIZE];
};
typedef struct file_packet file_packet;

#define NEW 1
#define DEL 2
#define UPD 3  // update?  maybe something for later...

struct file_update {
	int mode;
	char file_name[MAXNAME];
};
typedef struct file_update file_update;


struct download_1_argument {
	char *file_name;
	int idx;
};
typedef struct download_1_argument download_1_argument;

#define PEER_NODE_PROG 1000
#define PEER_NODE_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define download 1
extern  file_packet * download_1(char *, int , CLIENT *);
extern  file_packet * download_1_svc(char *, int , struct svc_req *);
#define update_list 2
extern  int * update_list_1(CLIENT *);
extern  int * update_list_1_svc(struct svc_req *);
#define get_version 3
extern  int * get_version_1(CLIENT *);
extern  int * get_version_1_svc(struct svc_req *);
#define get_update 4
extern  file_update * get_update_1(int , CLIENT *);
extern  file_update * get_update_1_svc(int , struct svc_req *);
#define getLoad 5
extern  int * getload_1(CLIENT *);
extern  int * getload_1_svc(struct svc_req *);
#define Ping 99
extern  bool_t * ping_1(CLIENT *);
extern  bool_t * ping_1_svc(struct svc_req *);
extern int peer_node_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define download 1
extern  file_packet * download_1();
extern  file_packet * download_1_svc();
#define update_list 2
extern  int * update_list_1();
extern  int * update_list_1_svc();
#define get_version 3
extern  int * get_version_1();
extern  int * get_version_1_svc();
#define get_update 4
extern  file_update * get_update_1();
extern  file_update * get_update_1_svc();
#define getLoad 5
extern  int * getload_1();
extern  int * getload_1_svc();
#define Ping 99
extern  bool_t * ping_1();
extern  bool_t * ping_1_svc();
extern int peer_node_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_file_packet (XDR *, file_packet*);
extern  bool_t xdr_file_packet (XDR *, file_packet*);
extern  bool_t xdr_file_update (XDR *, file_update*);
extern  bool_t xdr_file_update (XDR *, file_update*);
extern  bool_t xdr_download_1_argument (XDR *, download_1_argument*);

#else /* K&R C */
extern bool_t xdr_file_packet ();
extern bool_t xdr_file_packet ();
extern bool_t xdr_file_update ();
extern bool_t xdr_file_update ();
extern bool_t xdr_download_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PEER_NODE_H_RPCGEN */
