/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "peer_node.h"
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static file_packet *
_download_1 (download_1_argument *argp, struct svc_req *rqstp)
{
	return (download_1_svc(argp->file_name, argp->idx, rqstp));
}

static int *
_update_list_1 (void  *argp, struct svc_req *rqstp)
{
	return (update_list_1_svc(rqstp));
}

static int *
_get_version_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_version_1_svc(rqstp));
}

static file_update *
_get_update_1 (int  *argp, struct svc_req *rqstp)
{
	return (get_update_1_svc(*argp, rqstp));
}

static int *
_getload_1 (void  *argp, struct svc_req *rqstp)
{
	return (getload_1_svc(rqstp));
}

static bool_t *
_ping_1 (void  *argp, struct svc_req *rqstp)
{
	return (ping_1_svc(rqstp));
}

static void
peer_node_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		download_1_argument download_1_arg;
		int get_update_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case download:
		_xdr_argument = (xdrproc_t) xdr_download_1_argument;
		_xdr_result = (xdrproc_t) xdr_file_packet;
		local = (char *(*)(char *, struct svc_req *)) _download_1;
		break;

	case update_list:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _update_list_1;
		break;

	case get_version:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _get_version_1;
		break;

	case get_update:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_file_update;
		local = (char *(*)(char *, struct svc_req *)) _get_update_1;
		break;

	case getLoad:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _getload_1;
		break;

	case Ping:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) _ping_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	// This file is not supposed to be changed according to rpcgen
	// The following comments indicate what changes were made...

	///////////  START NEW CODE //////////

	if(argc < 3) {
		printf("%s <server_port> <latency>\n", argv[0]);
		return 1;
	}
	int local_port = atoi(argv[1]);
	latency = atoi(argv[2]);

	// Make a socket
	int server_fd;
    if ((server_fd = socket(AF_INET, SOCK_DGRAM, 0)) == 0) {
        perror("socket");
        return 1;
    }
	int opt = 1;
    if (setsockopt(server_fd, SOL_SOCKET, SO_REUSEADDR | SO_REUSEPORT, &opt, sizeof(int))) {
        perror("setsockopt");
        return 1;
    }

	// Setup and bind to port argv[1]
	struct sockaddr_in address;
    address.sin_family = AF_INET;
    address.sin_addr.s_addr = INADDR_ANY;
    address.sin_port = htons(local_port);

    if (bind(server_fd, (struct sockaddr *)&address, sizeof(address)) < 0) {
        perror("bind");
        return (1);
    }
	printf("Socket up and running on port %s!\n", argv[1]);

	///////////  END NEW CODE //////////


	register SVCXPRT *transp;

	pmap_unset (PEER_NODE_PROG, PEER_NODE_VERSION);

	transp = svcudp_create(server_fd);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, PEER_NODE_PROG, PEER_NODE_VERSION, peer_node_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (PEER_NODE_PROG, PEER_NODE_VERSION, udp).");
		exit(1);
	}

	// TCP RPC communication, commented out since not using
	// transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	// if (transp == NULL) {
	// 	fprintf (stderr, "%s", "cannot create tcp service.");
	// 	exit(1);
	// }
	// if (!svc_register(transp, PEER_NODE_PROG, PEER_NODE_VERSION, peer_node_prog_1, IPPROTO_TCP)) {
	// 	fprintf (stderr, "%s", "unable to register (PEER_NODE_PROG, PEER_NODE_VERSION, tcp).");
	// 	exit(1);
	// }

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
